# Generated by Django 4.0.3 on 2022-04-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JuegosDeConsola',
            fields=[
                ('idJuegosDeConsola', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fechaDeLanzamiento', models.DateField()),
                ('generos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JuegosDePc',
            fields=[
                ('idJuegos', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fechaDeLanzamiento', models.DateField()),
                ('generos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('idNoticia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.CharField(max_length=500)),
            ],
        ),
    ]
