# Generated by Django 4.0.3 on 2022-05-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juegosdeconsola',
            old_name='generos',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='juegosdepc',
            old_name='generos',
            new_name='genero',
        ),
        migrations.AddField(
            model_name='juegosdeconsola',
            name='consola',
            field=models.CharField(default='nscs', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegosdeconsola',
            name='sinopsis',
            field=models.CharField(default='sin definir', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='juegosdepc',
            name='sinopsis',
            field=models.CharField(default='sin definir', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticias',
            name='subtitulo',
            field=models.CharField(default='sin definir', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticias',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
