# Generated by Django 4.0.3 on 2022-05-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_generos_juegosdeconsola_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegosdepc',
            name='idJuegos',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
