# Generated by Django 4.0.3 on 2022-05-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_juegosdepc_idjuegos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='cuerpo',
            field=models.CharField(max_length=1500),
        ),
    ]
