# Generated by Django 4.0.3 on 2022-05-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_avatar_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='profile1.jpg', null=True, upload_to='profile'),
        ),
    ]
