# Generated by Django 4.0.3 on 2022-05-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_avatar_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('idBlog', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField(blank='True', null='True')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen')),
                ('imagenFecha', models.DateField()),
            ],
        ),
    ]
